export default {
  "widgetList": [
    {
      "key": 66701,
      "type": "date",
      "icon": "date-field",
      "formItemFlag": true,
      "options": {
        "name": "date110330",
        "label": "date",
        "labelAlign": "",
        "type": "date",
        "defaultValue": "",
        "placeholder": "",
        "columnWidth": "200px",
        "size": "",
        "autoFullWidth": true,
        "labelWidth": null,
        "labelHidden": false,
        "readonly": false,
        "disabled": false,
        "hidden": false,
        "clearable": true,
        "editable": false,
        "format": "YYYY-MM-DD HH:mm",
        "valueFormat": "YYYY-MM-DD HH:mm",
        "defaultTime": "2000-01-01 00:00:00",
        "required": false,
        "requiredHint": "",
        "validation": "",
        "validationHint": "",
        "customClass": [],
        "labelIconClass": null,
        "labelIconPosition": "rear",
        "labelTooltip": null,
        "onCreated": "",
        "onMounted": "",
        "onChange": "",
        "onFocus": "",
        "onBlur": "",
        "onValidate": "",
        "onDisabledDate": "return dateTime.getTime() <  new Date().getTime()"
      },
      "id": "date110330"
    },
    {
      "key": 12248,
      "type": "date-range",
      "icon": "date-range-field",
      "formItemFlag": true,
      "options": {
        "name": "daterange64355",
        "label": "date-range",
        "labelAlign": "",
        "type": "daterange",
        "defaultValue": null,
        "startPlaceholder": "",
        "endPlaceholder": "",
        "columnWidth": "200px",
        "size": "",
        "autoFullWidth": true,
        "labelWidth": null,
        "labelHidden": false,
        "readonly": false,
        "disabled": false,
        "hidden": false,
        "clearable": true,
        "editable": false,
        "format": "YYYY-MM-DD",
        "valueFormat": "YYYY-MM-DD HH:mm",
        "defaultTime": [
          "2000-01-01 00:00:00",
          "2000-01-01 23:59:00"
        ],
        "required": false,
        "requiredHint": "",
        "validation": "",
        "validationHint": "",
        "customClass": [],
        "labelIconClass": null,
        "labelIconPosition": "rear",
        "labelTooltip": null,
        "onCreated": "",
        "onMounted": "",
        "onChange": "",
        "onFocus": "",
        "onBlur": "",
        "onValidate": "",
        "onDisabledDate": ""
      },
      "id": "daterange64355"
    }
  ],
  "formConfig": {
    "modelName": "formData",
    "refName": "vForm",
    "rulesName": "rules",
    "labelWidth": 80,
    "labelPosition": "left",
    "size": "",
    "labelAlign": "label-left-align",
    "cssCode": "",
    "customClass": [],
    "functions": "",
    "layoutType": "PC",
    "jsonVersion": 3,
    "onFormCreated": "",
    "onFormMounted": "",
    "onFormDataChange": ""
  }
}
